#!/usr/bin/env bash
# Print frontend env vars for deployed Beratheon testnet contracts.
set -euo pipefail

DEPLOYER="${BERATHEON_DEPLOYER:-ST30PNQ7ZP471GY3BDM0XFT48EA5WC5GTQ0PG3XHR}"

cat <<EOF
# Add to frontend-next/.env.local after testnet deploy:
NEXT_PUBLIC_STACKS_NETWORK=testnet
NEXT_PUBLIC_BERATHEON_TREASURY=ST2Y1HES6JR37ZFVZWCPTZWEE0WG79G3Y8VV3EE29
NEXT_PUBLIC_BERATHEON_DEPLOYER=${DEPLOYER}
NEXT_PUBLIC_TRAITS_CONTRACT=${DEPLOYER}.traits
NEXT_PUBLIC_ITEMS_SFT_CONTRACT=${DEPLOYER}.items-sft
NEXT_PUBLIC_HONEY_TOKEN_CONTRACT=${DEPLOYER}.honey-token
NEXT_PUBLIC_JUICE_TOKEN_CONTRACT=${DEPLOYER}.juice-token
NEXT_PUBLIC_CUB_NFT_CONTRACT=${DEPLOYER}.cub-nft
NEXT_PUBLIC_USERNAME_NFT_CONTRACT=${DEPLOYER}.username-nft
NEXT_PUBLIC_NOOB_PASS_CONTRACT=${DEPLOYER}.noob-pass
NEXT_PUBLIC_GAME_REGISTRY_CONTRACT=${DEPLOYER}.game-registry
NEXT_PUBLIC_GAME_AUTHORITY_CONTRACT=${DEPLOYER}.game-authority
NEXT_PUBLIC_MARKETPLACE_CONTRACT=${DEPLOYER}.marketplace
NEXT_PUBLIC_CRAFTING_CONTRACT=${DEPLOYER}.crafting
NEXT_PUBLIC_CONQUEST_CONTRACT=${DEPLOYER}.conquest
NEXT_PUBLIC_ECHOES_CONTRACT=${DEPLOYER}.echoes
NEXT_PUBLIC_HELPERS_CONTRACT=${DEPLOYER}.helpers
EOF
